export enum activityKnowledge {
  identifyStudies = 'identifyStudies',
  rewiewEvidence = 'rewiewEvidence',
  produceGuidance = 'produceGuidance',
  makeGuidance = 'makeGuidance',
  implementGuidance = 'implementGuidance',
  analyzeResults = 'analyzeResults',
  applyResults = 'applyResults',
}

export enum categories {
  features = 'features',
  diagnoses = 'diagnoses',
  diagnostics = 'diagnostics',
  comorb = 'comorb',
  caremgmt = 'caremgmt',
  specpop = 'specpop',
  therapeuticsandprevention = 'therapeuticsandprevention',
  resmgmt = 'resmgmt',
  logistics = 'logistics',
  ppe = 'ppe',
  control = 'control',
  pubhealthcaserep = 'pubhealthcaserep',
  epid = 'epid',
  cliepid = 'cliepid',
  subjectreserch = 'subjectreserch',
  ethics = 'ethics',
  prevention = 'prevention',
  screening = 'screening',
  diagnosis = 'diagnosis',
  treatment = 'treatment',
  followup = 'followup',
  trial = 'trial',
  research = 'research',
  authoring = 'authoring',
  implementation = 'implementation',
  collaboration = 'collaboration',
  home = 'home',
  telemedicine = 'telemedicine',
  ambulatory = 'ambulatory',
  acute = 'acute',
  laboratoryenv = 'laboratoryenv',
  longtermcare = 'longtermcare',
  postacutecare = 'postacutecare',
  datavis = 'datavis',
  datacol = 'datacol',
  list = 'list',
  knowledge = 'knowledge',
  policy = 'policy',
  recommend = 'recommend',
  guideline = 'guideline',
  rules = 'rules',
  workflow = 'workflow',
  model = 'model',
  systemrev = 'systemrev',
  assertion = 'assertion',
}

export enum role {
  directCare = 'directCare',
  publicHealth = 'publicHealth',
  administration = 'administration',
  patient = 'patient',
  research = 'research',
}

export enum formalism {
  narrative = 'narrative',
  executable = 'executable',
  formalModel = 'formalModel',
  terminology = 'terminology',
  dataTypes = 'dataTypes',
  apis = 'apis',
  other = 'other',
}
